[package]
name = "portfolio-client"
version = "0.1.0"
edition = "2024"

[dependencies]
portfolio-common = { path = "../common" }
web-sys = "0.3.77"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
serde = "1.0.219"
serde_json = "1.0.141"
gloo-net = "0.6.0"
