# TODO: Fix
# [[hooks]]
# stage = "post_build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss -i ./styles/tailwind.css -o ./dist/.stage/index.css"]

[[proxy]]
backend = "http://localhost:8000/api"
